# Setup
title:        John Webster - Blog
tagline:      JavaScript Frameworks  &middot;  Experiments  &middot;  Web Development
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       John Webster
  url:       https://github.com/johnfrog76

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
pattern = GeoPattern.generate('Mastering Markdown', patterns: :sine_waves)
